Repository obsidianmd/obsidian-help, pull requests merged in 2023-03, with the labels that each got.

#408 Fix community feedback
  en/Contributing to Obsidian/Financial contributions.md
  en/Developers/Build themes.md
  en/Extending Obsidian/Plugin security.md
  en/Licenses & Payment/Catalyst license.md
  en/Licenses & Payment/Commercial license.md
  en/Licenses & Payment/Education and non-profit discount.md
  en/Licenses & Payment/Refund policy.md
  en/Start here.md
Labels: kind/update

#403 Redirect refactored pages
  en/Editing and formatting/Callouts.md
  en/Editing and formatting/HTML sanitization.md
  en/Editing and formatting/Metadata.md
  en/Editing and formatting/Multiple cursors.md
  en/Editing and formatting/Tags.md
  en/Licenses and payment/Catalyst license.md
  en/Licenses and payment/Commercial license.md
  en/Licenses and payment/Education and non-profit discount.md
  en/Licenses and payment/Gifting.md
  en/Licenses and payment/Obsidian Credit.md
  en/Licenses and payment/Refund policy.md
  en/Linking notes and files/Aliases.md
  en/Linking notes and files/Embedding files.md
  en/Linking notes and files/Internal links.md
  en/Plugins/Backlinks.md
Labels: kind/refactor

#415 Add Redirecting old notes docs
  en/Obsidian Publish/Redirecting old notes.md
Labels: kind/new

#406 Da: Sync/Publish + some additional translations
  da/Hjælp og support.md
  da/Obsidian Publish/Administration af websteder.md
  da/Obsidian Publish/Deling af bokse.md
  da/Obsidian Publish/Hosting af mediefiler.md
  da/Obsidian Publish/Introduktion til Obsidian Publish.md
  da/Obsidian Publish/Opsætning af Google Analytics.md
  da/Obsidian Publish/Opsætning af Obsidian Publish.md
  da/Obsidian Publish/Opsætning på eget domæne.md
  da/Obsidian Publish/Publicer og håndter udgivelser af noter.md
  da/Obsidian Publish/Sikkerhed og privatliv.md
  da/Obsidian Publish/Tilpas dit websted.md
  da/Obsidian Sync/Begrænsninger.md
  da/Obsidian Sync/Deling af fjernbokse.md
  da/Obsidian Sync/Fejlsøg Obsidian Sync.md
  da/Obsidian Sync/Introduktion til Obsidian Sync.md
  da/Obsidian Sync/Lokal- og fjernbokse.md
  da/Obsidian Sync/Obsidian Sync og tredjeparts services.md
  da/Obsidian Sync/Opsætning af Obsidian Sync på en anden enhed.md
  da/Obsidian Sync/Opsætning af Obsidian Sync.md
  da/Obsidian Sync/Sikkerhed og privatliv.md
  da/Obsidian Sync/Versionshistorik.md
  da/Obsidian Sync/Vælge filer og indstillinger til Sync.md
  da/Obsidian/Android app.md
  da/Obsidian/Indeks.md
  da/Obsidian/Obsidian.md
  da/Obsidian/Tak til.md
  da/Plugins/Canvas.md
  da/Redigering og formatering/Sammenfoldning.md
  da/Start her.md
  da/Sådan gør du/Arbejde med flere noter.md
  da/Sådan gør du/Sammenfoldning.md
  da/Sådan gør du/Tilføj brugerdefinerede temaer.md
  da/Vedhæftninger/Slide demo.md
Labels: translation/da

#409 Refactor How to pages
  en/Customization/Custom hotkeys.md
  en/Editing and formatting/Embedding web pages.md
  en/Editing and formatting/Folding.md
  en/Getting started/Update Obsidian.md
  en/How to/Change settings.md
  en/How to/Format your notes.md
  en/How to/Read and edit modes.md
  en/How to/Update Obsidian.md
  en/How to/Use hotkeys.md
  en/How to/Working with multiple notes.md
  en/Obsidian/Index.md
  en/Start here.md
Labels: kind/refactor

#410 Editing and previewing Markdown
  en/Editing and formatting/Editing and previewing Markdown.md
  en/Editing and formatting/Metadata.md
  en/User interface/Workspace/Panes/Linked pane.md
Labels: kind/refactor

#400 Update Sync your notes across devices.md
  en/Getting started/Sync your notes across devices.md
Labels: area/sync, kind/update

#424 Update style guide with arrow type
  en/Contributing to Obsidian/Style guide.md
  en/Editing and formatting/Editing and previewing Markdown.md
  en/Getting started/Sync your notes across devices.md
  en/Getting started/Update Obsidian.md
  en/Licenses and payment/Catalyst license.md
  en/Licenses and payment/Commercial license.md
  en/Licenses and payment/Education and non-profit discount.md
  en/Obsidian Sync/Select files and settings to sync.md
  en/Obsidian Sync/Troubleshoot Obsidian Sync.md
  en/Plugins/File explorer.md
  en/Plugins/File recovery.md
Labels: kind/update
