Repository obsidianmd/obsidian-help, pull requests merged in 2023-05, with the labels that each got.

#451 Update Sync limitations
  en/Obsidian Sync/Limitations.md
Labels: area/sync, kind/update

#456 Add docs for Bookmarks plugin
  en/Advanced topics/Drag and Drop.md
  en/Plugins/Bookmarks.md
  en/Plugins/Core plugins.md
  en/Plugins/Starred.md
Labels: kind/new

#467 Add Glossary
  en/Getting started/Glossary.md
Labels: kind/new

#470 Update contribution guidelines
  README.md
  en/Contributing to Obsidian/Translations.md
Labels: kind/refactor

#471 Update list of translations
  README.md
  en/Home.md
  pt-br/Home.md
Labels: kind/update

#472 Add docs for indenting code blocks
  en/Editing and formatting/Basic formatting syntax.md
Labels: kind/update

#473 Slides: Remove broken link
  en/Plugins/Slides.md
Labels: kind/update

#476 Add references to the developer docs
  en/Contributing to Obsidian/Developers.md
  en/Developers/Build plugins.md
  en/Developers/Build themes.md
  en/Extending Obsidian/CSS snippets.md
  en/Extending Obsidian/Community plugins.md
  en/Extending Obsidian/Themes.md
  en/Obsidian Publish/Customize your site.md
  en/Plugins/Core plugins.md
Labels: kind/update

#478 Update Embedding web pages for Obsidian 1.3
  en/Editing and formatting/Embedding web pages.md
Labels: kind/update

#479 Deprecate How tos
  en/Customization/Appearance.md
  en/Extending Obsidian/Themes.md
  en/How to/Add custom styles.md
  en/How to/Read and edit modes.md
  en/How to/Working with multiple vaults.md
Labels: kind/refactor

#481 Fix wording for embedding videos and tweets
  en/Editing and formatting/Embedding web pages.md
Labels: kind/update
